config/routes.rb
# frozen_string_literal: true
Rails.application.routes.draw do
  devise_for :users
  get 'categories/new'

  namespace :admin do
    resources :articles
    resources :users
    resources :categories
    resources :subcategories
    resources :article_blocks
    resources :article_text_blocks
    resources :article_image_blocks
    resources :article_diagram_blocks
    resources :article_equation_blocks
    resources :equation_block_variables
    resources :article_link_blocks
    resources :contributors
    resources :categorizations
    resources :diagrams
    resources :images

    root to: 'articles#index'
  end
  get '/about' => 'static_pages#about'
  root to: 'static_pages#home'
  resources :articles
  resources :article_diagram_blocks, only: :show
  resources :images, only: :create
  # categories
  resources :categories
  resources :subcategories
  resources :categorizations
end

app/controllers/static_pages_controller.rb
# frozen_string_literal: true
# Controller to display static pages.
class StaticPagesController < ApplicationController
  def about
  end

  def home
  end
end

app/helpers/static_pages_helper.rb
# frozen_string_literal: true
module StaticPagesHelper
end

app/views/static_pages/_footer.html.erb
<!-- designed by Kyle Colle-Tripp and Omid Ghiyasian
     from the front-end team -->

<div class='container-fluid footerContent'>
  <span>&copy; <%= DateTime.now.strftime('%Y') %> &dash; Wilfrid Laurier University</span>
</div>

app/views/static_pages/_header.html.erb
<meta name='viewport' content='width=device-width, initial-scale=1.0'>
<nav class='navbar navbar-inverse navbar-static-top'>
  <div class='container'>
    <div class='navbar-header'>
      <button type='button' class='navbar-toggle collapsed'
        data-toggle='collapse' data-target='#navbar' aria-expanded='false'
        aria-controls='navbar'>
      <span class='sr-only'>Toggle navigation</span>
      <span class='icon-bar'></span>
      <span class='icon-bar'></span>
      <span class='icon-bar'></span>
      </button>
      <%= link_to root_path, class: 'navbar-brand' do %>
        <%= image_tag 'upod_logo_color_v2.png', width: 100 %>
      <% end %>
    </div>
    <div id='navbar' class='navbar-collapse collapse'>
      <ul class='nav navbar-nav'>
        <li class='dropdown mega-dropdown'>
          <a href='#' class='dropdown-toggle' style='width:auto;'
            data-toggle='dropdown'>
            Categories
            <span class='caret'></span>
          </a>
          <ul class='dropdown-menu mega-dropdown-menu row'>
            <% @categories.each do |category| %>
            <li class='col-sm-2'>
              <ul>
                <li>
                 <%= link_to category.name, category,
                                            :class => 'dropdown-header' %>
                </li>
                <% category.subcategories.each do |subcategory| %>
                  <li>
                    <%= link_to subcategory.name, subcategory %>
                  </li>
                <% end %>
              </ul>
            </li>
            <% end %>
          </ul>
        </li>
        <li>
          <%= link_to 'About', about_path, :style => 'width:auto;' %>
        </li>
        <li>
          <%= link_to 'Articles', articles_path, :style => 'width:auto;' %>
        </li>
        </ul>
        <ul class='nav navbar-nav navbar-right'>
          <% unless current_page?(root_path) %>
          <!-- nav search -->
          <li>
            <%= form_tag articles_path, { role: :search,
                         class: 'navbar-form', method: :get,
                         style: 'margin-right:auto;margin-left:auto;' } do %>
              <ul class='input-group'>
                <%= render partial: 'static_pages/search_form', locals: { autofocus: false } %>
              </ul>
            <% end %>
          </li>
          <% end %>
          <%# Registration Links %>
          <% if user_signed_in? %>
            <li>
              <%= link_to('Admin', admin_articles_path,
                                   style: 'width:auto;')  %>
            </li>
            <li>
              <%= link_to('Sign Out', destroy_user_session_path,
                                      :method => :delete,
                                      style: 'width:auto;') %>
            </li>
          <% end %>
        </ul>
    </div>
  </div>
</nav>

app/views/static_pages/_search_form.html.erb
<span class='input-group-btn'>
  <%= select_tag :cat_id,
      options_from_collection_for_select(Category.all, :id, :name),
      {prompt: 'All',
      :class => 'btn btn-default resizeselect',
      :style => '-moz-appearance: none; -webkit-appearance: none;'} %>
</span>
<%= text_field_tag :q, params[:q], class: 'form-control', autofocus: autofocus || false %>
<span class='input-group-btn'>
  <%= button_tag(type: :submit, class: 'btn btn-default') do %>
    <span class='glyphicon glyphicon-search'> </span>
  <% end %>
</span>

app/views/static_pages/_search_form_header.html.erb
<span class='input-group-btn'>
  <%= select_tag :cat_id,
      options_from_collection_for_select(Category.all, :id, :name),
      {prompt: 'All',
      :class => 'btn btn-default resizeselect',
      :style => '-moz-appearance: none; -webkit-appearance: none;'} %>
</span>
<%= text_field_tag :q, params[:q], class: 'form-control', autofocus: false %>
<span class='input-group-btn'>
  <%= button_tag(type: :submit, class: 'btn btn-default') do %>
    <span class='glyphicon glyphicon-search'> </span>
  <% end %>
</span>

app/views/static_pages/about.html.erb
<% title "About" %>
<div class="container", style="margin-bottom:150px;">
  <h1 class="page-header">ABOUT UPOD</h1>
	<p style="font-size:1.2em;">Welcome to the Undergraduate Physics Online Database. UPOD was created by undergraduate students at Wilfrid Laurier University under the supervision of Dr. Shohini Ghose in order to provide college and university students with a complete reference guide to undergraduate physics topics. Whether you are an upper-year physics major or a first-year taking a physics related elective, UPOD will remind you of what you've forgotten, clarify what confuses you, and reinforce your physics background. Can't remember Newton's third law? Want to brush up on the photoelectric effect? You've come to the right place. If you know what you're looking for, then you may want to try the search engine at the top of the page. Or, you can browse our database by clicking on any of the six main topics and scrolling through the list of subsections to zero in on exactly what you need. Good luck, and may all the forces be with you!</p>

	<p style="font-size:1.2em;">UPOD was generously supported by the Laurier Academic Development Fund and the Laurier Department of Physics and Computer Science</p>
</div>

app/views/static_pages/home.html.erb
<body style='background-color:#390080;'>
  <div class='col-md-6 col-md-offset-3' style="margin-top:5%;">
    <%= link_to root_path do %>
      <%= image_tag('logo.png', :class => 'center-block',
      :style => 'max-width: 98%; margin-top: 5%; margin-bottom: 40px;')%>
    <% end %>
  </div>
  <div class='col-md-6 col-md-offset-3'>
    <%= form_tag articles_path, method: :get, role: 'search' do %>
      <div class='form-group' style='display:inline;'>
        <div class='input-group'>
          <%= render partial: 'static_pages/search_form', locals: { autofocus: true } %>
        </div> <!-- .input-group -->
      </div> <!-- .form-group -->
    <% end %>
  </div>
</body>