config/routes.rb
# frozen_string_literal: true
Rails.application.routes.draw do
  devise_for :users
  get 'categories/new'

  namespace :admin do
    resources :articles
    resources :users
    resources :categories
    resources :subcategories
    resources :article_blocks
    resources :article_text_blocks
    resources :article_image_blocks
    resources :article_diagram_blocks
    resources :article_equation_blocks
    resources :equation_block_variables
    resources :article_link_blocks
    resources :contributors
    resources :categorizations
    resources :diagrams
    resources :images

    root to: 'articles#index'
  end
  get '/about' => 'static_pages#about'
  root to: 'static_pages#home'
  resources :articles
  resources :article_diagram_blocks, only: :show
  resources :images, only: :create
  # categories
  resources :categories
  resources :subcategories
  resources :categorizations
end

app/models/Article/article_block.rb
# frozen_string_literal: true
# An article is made up of many ArticleBlocks. This class is the parent
# class of various types of article blocks (ArticleBlock is actable). Other
# article blocks inherit ArticleBlock's attributes, methods and validations.
# Each ArticleBlock has a one-to-one connection with an {Article}
# @see Article
# @see ArticleDiagramBlock
# @see ArticleEquationBlock
# @see ArticleImageBlock
# @see ArticleLinkBlock
# @see ArticleTextBlock
#
# author: Michael Roher, Kieran O'Driscoll (Validations), Steven Swartz
#
# == Schema Information
#
# Table name: article_blocks
#
#  id           :integer          not null, primary key
#  position     :integer
#  article_id   :integer
#  actable_id   :integer          not null
#  actable_type :string(255)
#
class ArticleBlock < ActiveRecord::Base
  # sets ArticleBlock to actable
  actable
  # Makes ArticleBlock belong to Article
  belongs_to :article
  # The scope restricts it to the article id
  acts_as_list scope: :article_id

  # Used to resolve partials in views e.g. ArticleTextBlock => text_block
  def slug
    specific.class.to_s.underscore.split('article_').last
  end
end

app/models/Article/article_diagram_block.rb
# frozen_string_literal: true
# ArticleDiagramBlock is a more specific {ArticleBlock}.
# It contains a diagram ID which links to a specific diagram
# ArticleDigramBlock belongs to {Diagram} and acts as an article block.
# It inherits ArticleBlock's attributes, methods and validations. As well
# has a one-to-one connections with {Diagram}.
# @see Diagram
# @see ArticleBlock
#
# author: Michael Roher, Kieran O'Driscoll (Validations), Steven Swartz (Implementation)
#
# == Schema Information
#
# Table name: article_diagram_blocks
#
#  id         :integer          not null, primary key
#  diagram_id :integer
#  code :text
#  caption :string(255)
#  height :integer
#  width  :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
class ArticleDiagramBlock < ActiveRecord::Base
  belongs_to :diagram
  acts_as :article_block

  # based on http://www.w3schools.com/browsers/browsers_display.asp
  MAX_WIDTH = 1080
  MAX_HEIGHT = 1920

  validates :code, presence: true, length: { maximum: 65_535 }
  validates :caption, length: { maximum: 255 }
  validates :height, presence: true, numericality: { only_integer: true, greater_than: 0, less_than_or_equal_to: MAX_HEIGHT }
  validates :width, presence: true, numericality: { only_integer: true, greater_than: 0, less_than_or_equal_to: MAX_WIDTH }

  # Used by SirTrevor for editing this block
  def as_json
    {
      type: :diagram,
      data:
        {
          caption: caption,
          code: code,
          width: width,
          height: height
        }
    }
  end
end

app/models/Article/article_equation_block.rb
# frozen_string_literal: true
# ArticleEquationBlock is a more specific {ArticleBlock}. It represents
# an equation which has many {EquationBlockVariable} which encapsulate
# a mathematical expression with descriptions of variables that it includes.
# It inherits ArticleBlock's attributes, methods and validations.
#
# @see ArticleBlock
# @see EquationBlockVariables
#
# author: Michael Roher, Kieran O'Driscoll (Validations), Steven Swartz (Implementation)
#
# == Schema Information
#
# Table name: article_equation_blocks
#
#  id       :integer          not null, primary key
#  equation :text
#  label    :string(255)
#
class ArticleEquationBlock < ActiveRecord::Base
  acts_as :article_block
  has_many :equation_block_variables, dependent: :destroy

  # Validates the length and presence of equation block and description
  validates :equation, presence: true, length: { maximum: 65_535 }
  validates :label, length: { maximum: 255 }, presence: true

  # Used by SirTrevor for editing this block
  # Get each variable associated with this equation and add each of their
  # hashes to the variables hash
  def as_json
    variables = {}
    equation_block_variables.each_with_index do |variable, index|
      variables[index] = variable.as_json
    end

    {
      type: :equation,
      data: { equation: equation, label: label, variables: variables }
    }
  end
end

app/models/Article/article_image_block.rb
# frozen_string_literal: true
# ArticleImageBlock is a more specific {ArticleBlock}.
# It inherits ArticleBlock's attributes, methods and validations. It also has a
# one-to-one connection with {Image}
# @see ArticleBlock
# @see Image
#
# author: Michael Roher, Kieran O'Driscoll (Validations)
#
#
# == Schema Information
#
# Table name: article_image_blocks
#
#  id         :integer          not null, primary key
#  image_id   :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
class ArticleImageBlock < ActiveRecord::Base
  belongs_to :image
  acts_as :article_block

  def image_url(size = nil)
    image.body.url(size)
  end

  def as_json
    {
      id: image.id,
      type: :image,
      data: {
        file: {
          url: image_url
        }
      }
    }
  end
end

app/models/Article/article_link_block.rb
# frozen_string_literal: true
# ArticleLinkBlock is a more specific {ArticleBlock}.
# It contains an id, a source and a video id. ArticleLinkBlock acts as an
# article block. If more video formats are supported in the future, this class
# would be easier to maintain if it was abstract and inherited by each video
# format. With only 2 video formats, inheritance would add unneeded complexity.
#
# @see ArticleBlock
#
# author: Michael Roher, Kieran O'Driscoll (Validations), Steven Swartz
#
# == Schema Information
#
# Table name: article_link_blocks
#
#  id       :integer          not null, primary key
#  source   :string(255)
#  video_id :string(255)      not null
#
class ArticleLinkBlock < ActiveRecord::Base
  acts_as :article_block

  # validates the presence and length of the url block and label
  validates :source, presence: true, length: { maximum: 255 }
  validates :video_id, presence: true, length: { maximum: 255 }
  validate :video_source_must_be_in_list, :video_id_must_match_pattern

  # contains the acceptable sources and their corresponding character
  # set for a valid video_id
  SOURCE_PATTERNS = \
    Hash['youtube' => /^[A-Za-z0-9_-]{11}$/, 'vimeo' => /^[0-9]*$/]

  # Checks to see if the video source is either youtube or vimeo
  #
  # @return [Boolean] Whether the source was found in the hash
  def video_source_must_be_in_list
    unless SOURCE_PATTERNS.key?(source)
      errors.add(:source, 'video is from an unsupported website')
    end
  end

  # Checks to see if the video id is valid based on the video's source
  #
  # @return [Boolean] Whether the video id is valid
  def video_id_must_match_pattern
    if SOURCE_PATTERNS.key?(source) && !SOURCE_PATTERNS[source].match(video_id)
      errors.add(:video_id, 'invalid video link provided')
    end
  end

  # Returns the url to use when embedding the video in an iframe
  #
  # @return [String] url to use in src of iframe
  def embeddable_url
    return 'https://www.youtube.com/embed/' + video_id if source == 'youtube'
    return 'https://player.vimeo.com/video/' + video_id if source == 'vimeo'
  end

  # Returns the direct url to this video
  #
  # @return [String] url to use in src of iframe
  def direct_url
    return 'https://www.youtube.com/watch?v=' + video_id if source == 'youtube'
    return 'https://vimeo.com/' + video_id if source == 'vimeo'
  end

  # Used by SirTrevor for editing this block
  def as_json
    {
      type: :link,
      data:
      {
        source: source,
        video_id: video_id,
        url: direct_url
      }
    }
  end
end

app/models/Article/article_text_block.rb
# frozen_string_literal: true
# ArticleTestBlock is a more specific {ArticleBlock}.
# It is a generic block that contains a body attribute.
# Other blocks that can be represented by a single string
# should inherit this block and provide a unique partial html
# view when rendered in articles.
# The body of the text block is {Searchable}
#
# @see ArticleBlock
#
# author: Michael Roher, Kieran O'Driscoll (Validations), Steven Swartz
#
# == Schema Information
#
# Table name: article_text_blocks
#
#  id   :integer          not null, primary key
#  body :text(65535)
#  type :text(256)
#
class ArticleTextBlock < ActiveRecord::Base
  acts_as :article_block
  # single table inheritance of subclasses through the database column "type"
  self.inheritance_column = :type

  # Validates the presence and length of the body of title block
  validates :body, presence: true, length: { maximum: 65_535 }

  # Used by SirTrevor for updating
  def as_json
    {
      type: :text,
      data:
      {
        text: body,
        format: :html
      }
    }
  end
end

app/models/article.rb
# frozen_string_literal: true
# An Article is made up of many blocks and is the complete model. It contains
# various blocks that make up its' look and feel.
# An Article is {Blockable} as well as {Searchable}
#
# author: Michael Roher, Kieran O'Driscoll (Validations), Steven Swartz,
#         Robert Morouey.
#
# == Schema Information
#
# Table name: articles
#
#  id         :integer          not null, primary key
#  title      :string(255)
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
class Article < ActiveRecord::Base
  has_many :blocks, class_name: 'ArticleBlock', foreign_key: :article_id
  has_many :contributions, class_name: 'Contributor', foreign_key: :article_id
  has_many :categorizations, dependent: :destroy
  has_many :subcategories, through: :categorizations
  has_many :searches

  # Validates the title and it's length
  validates :title, presence: true, length: { maximum: 255 }

  # Reindex article class after changes
  after_commit :reindex_article

  # This include is defined in the blockable.rb concern. Essentially, it
  # provides a nice interface to interact with the various types of article
  # blocks. Instead of having to use the ArticleTextBlock, you can now use
  # article.create_text_block, ArticleEquationBlock is now
  # article.create_equation_block and so on and so forth.
  include Blockable
  include SirTrevorable
  extend FriendlyId

  searchkick \
    searchable:   %i(title body name label),
    match:        :word_start,
    callbacks:    :async

  friendly_id :slug_candidates, use: [:slugged, :finders]

  # Try building a slug based on the following fields in
  # increasing order of specificity.
  def slug_candidates
    [
      :title,
      [:title, :id],
    ]
  end


  # Replaces old blocks associated with this article with new ones
  # @param block_json [json] the sir trevor form data representing each block
  def change_blocks(block_json)

    #Removal of old blocks is rolled back on errors
    Article.transaction do
      blocks.destroy_all
      block_json.each do |block|
        create_block_from_sir_trevor(block)
      end
    end
  end

  # Replaces old subcategories associated with this article with new ones
  # @param subcategory_ids [int[]] a hash of the subcategory_ids to associate
  # with this article
  def change_subcategories(subcategory_ids)

    Article.transaction do
      #Removal of old categories are rolled back on errors
      categorizations.destroy_all
      subcategory_ids.each do |subcategory_id|
        categorizations.create(subcategory_id: subcategory_id)
      end
    end
  end

  # Returns the first n characters from the first text block in the article.
  def excerpt(length = 255)
    text_blocks = blocks.map { |b| b.specific.body if b.specific.respond_to?(:body) }
    ActionView::Base.full_sanitizer
    .sanitize(text_blocks.try(:first)
              .try(:first, length))
  end

  # Returns the data that will be flattened and indexed by the elastic search
  # core program
  # title = The title from each article
  # name = Name of each Category / Sub Category
  # label = labels from all the diagrams and images
  # category = id of the category which contain this article
  def search_data
    {
      title:        title,
      name:         blocks.map { |b| b.specific.name if b.specific.respond_to?(:name) },
      body:         blocks.map { |b| b.specific.body if b.specific.respond_to?(:body) },
      label:        blocks.map { |b| b.specific.label if b.specific.respond_to?(:label) },
      category:     subcategories.pluck(:category_id)
    }.as_json
  end

  private

  # Uses search_data method to re-index and flatten the searchable data in the
  # elastic search core
  def reindex_article
    Article.reindex
  end


end

app/controllers/admin/articles_controller.rb
# frozen_string_literal: true
# author: Kieran O'Driscoll(Organization and overriding methods)

module Admin
  class ArticlesController < Admin::ApplicationController
    # To customize the behavior of this controller,
    # simply overwrite any of the RESTful actions. For example:
    #
    # def index
    #   super
    #   @resources = Article.all.paginate(10, params[:page])
    # end

    # Define a custom finder by overriding the `find_resource` method:
    # def find_resource(param)
    #   Article.find_by!(slug: param)
    # end

    # See https://administrate-docs.herokuapp.com/customizing_controller_actions
    # for more information

    def new
      redirect_to new_article_url
    end

    def edit
      redirect_to edit_article_url
    end

    def show
      redirect_to article_path
    end
  end
end

app/controllers/articles_controller.rb
# frozen_string_literal: true
# Controller for /articles/ path.  Implements CRUD actions
class ArticlesController < ApplicationController
  # Include check_user
  before_action :set_article, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]
  after_action :reindex_articles_after_touching, only: [:create, :update, :destroy]
  skip_before_action :verify_authenticity_token, only: [:index, :show]
  # GET /articles
  def index
    redirect_to Category.find(params[:cat_id]) if cat_only?

    search_options = read_search_options
    search_options[:where] = { category: params[:cat_id] } \
    if params[:cat_id].present?

    @articles = Article.search params[:q], search_options
    end

  # GET /articles/1
  def show
    @article = Article.find(params[:id])
    search_options = read_search_options
    search_options[:operator] = 'or'
    query = @article.title.split(' ').select{|w| w.length >= 4} * (' ')
    @related = Article.search query, search_options
  end

  # GET /articles/new
  def new
    @article = Article.new
  end

  # GET /articles/1/edit
  def edit
    # used when populating checkboxes to avoid querying for each subcategory when determining if the article belongs to it
    @article_subcategory_ids = @article.subcategory_ids
  end

  # POST /articles
  def create
    @article = Article.create_from_sir_trevor(params[:sir_trevor_content], current_user)
    redirect_to @article
  end

  # PATCH/PUT /articles/1
  def update
    @article.update_from_sir_trevor!(params[:sir_trevor_content], current_user)
    redirect_to @article, success: 'Successfully updated #{@article.title}'
  end

  # DELETE /articles/1
  def destroy
    @article.destroy
    redirect_to articles_url, notice: 'Article was successfully destroyed.'
  end

  private

  def read_search_options
    {
      fields: %w(title^10 name body label),
      match: :word_start,
      misspellings: { edit_distance: 1 },
      # order: { _score: :desc },
      boost_where: { title: :exact }
    }
  end

  # Use callbacks to share common setup or constraints between actions.
  def set_article
    @article = Article.find(params[:id])
  end

  def cat_only?
    params[:cat_id].present? && params[:q].blank?
  end

  def reindex_articles_after_touching
    Article.reindex
  end
  end

app/helpers/articles/article_diagram_blocks_helper.rb
# frozen_string_literal: true
module Articles::ArticleDiagramBlocksHelper
end

app/helpers/articles/article_link_blocks_helper.rb
# frozen_string_literal: true
module Articles::ArticleLinkBlocksHelper
end

app/helpers/articles_helper.rb
# frozen_string_literal: true
module ArticlesHelper
end

app/views/articles/_articlefaq.html.erb
<%#
# Provides instructions for using the article builder to add content to
# articles
# Authors: Steven Swartz (Writing), Michael Roher (Styling),
#          Roman Lipisy (Styling)
%>
<div class="panel panel-default">
  <div class="panel-heading">
    <h4 class="panel-title">
      <a data-toggle="collapse" href="#article-faq">
        Help Me
        <i class="glyphicon glyphicon-chevron-right pull-right"></i>
        <i class="glyphicon glyphicon-chevron-down pull-right"></i>
      </a>
    </h4>
  </div><!-- panel-heading -->
  <div id="article-faq" class="panel-collapse collapse">
    <div class="panel-body">
      <h4>
        Using the Article Editor
      </h4>
      <h5>
        Mathematical Expressions
      </h5>
      <p>
        AsciiMath is the language used for creating mathematical expressions
        that are displayed in articles. Use
        <a href="http://asciimath.org/" target="_blank">
          their website
        </a>
        as a reference for inserting specific math symbols.
      </p>
      <h4>
        Block Types
      </h4>
      <h5>
        Text Blocks
      </h5>
      <p>
        Displays regular text and mathematical expressions on the same line.
        Enclose math with <code>`</code> (back-ticks) which will be rendered
        once you click outside of the text block you are editing or by clicking this icon:
      </p>
	   <i class='glyphicon glyphicon-eye-close text-muted'></i>
      <h5>
        Equation Blocks
      </h5>
      <p>
        Use this for describing important equations that are meant to stand out.
        You can optionally describe or define specific variables or symbols
        included in the equation by clicking "Add Variable Description"
      </p>

      <h5>
        Diagram Blocks
      </h5>
      <p>
        Custom html, svg, javascript, or css can be inserted into article.
        Certain functionality (alerts, form submission, etc.) will be blocked
        from executing when users view the content on the website for security
        purposes. In order to make the diagram scalable make sure you are using
	a viewbox to define its dimensions and make sure they match the dimensions
	of the iframe. Also make sure that you include html{overflow:hidden;} in your
	CSS style sheet if you have one, if you don't have one then you can make one
	just by typing <style></style> somewhere in the box.
      </p>
      <p>Code can be included:</p>
      <ul>
        <li>
          Directly in the textbox
        </li>
        <li>
          From external sources
        </li>
        <li>
          From local files which are located in the public folder of this
          website. For example, &lt;script src='/diagrams/script.js'&gt; would
          include the file at public/diagrams/script.js
        </li>
      </ul>
      <h5>
        Video Blocks
      </h5>
      <p>
        Videos from youtube or vimeo can be inserted into articles by providing
        their urls.
      </p>
    </div><!-- panel-body -->
  </div><!-- article-faq -->
</div><!-- panel-default -->

app/views/articles/_form.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-9">
      <form class="additional-sir-trevor-form">
        <div class="form-group">
          <strong><%= text_field_tag :title, article.try(:title),class: 'form-control input-lg', placeholder: 'Enter Article Title Here' %></strong>
        </div>
      </form>
      <%= form_tag article, method: article.new_record? ? :post : :patch, class: 'sir-trevor-form' do %>
        <%= text_area_tag :sir_trevor_content, article.try(:to_sir_trevor), class: 'js-sir-trevor-instance' %>
        <%= submit_tag 'Save Article', class: 'btn btn-success btn-block' %>
      <% end %>
    </div>
    <div class="col-md-3">
      <div class="panel-group">
        <div class="panel panel-default">
          <div class="panel-heading">
            <h4 class="panel-title">
              <a data-toggle="collapse" href="#subcategories-checkboxes">
                Add Subcategories
                <i class="glyphicon glyphicon-chevron-right pull-right"></i>
                <i class="glyphicon glyphicon-chevron-down pull-right"></i>
              </a>
            </h4>
          </div>
          <div id="subcategories-checkboxes" class="panel-collapse collapse">
            <div class="panel-body">
              <form class="additional-sir-trevor-form">
				<% Category.order(:name).each do |category| %>
					<b><p><%= category.name %></p></b>
					<%= collection_check_boxes(:article, :categorizations, category.subcategories.order(:name), :id, :name) do |b| %>
					  <div class="checkbox">
						<%= b.label do %>
						  <% #when editing, check if the article originally belonged to this subcategory and check the check_box if so %>
						  <%= b.check_box(checked: @article_subcategory_ids.present? && @article_subcategory_ids.include?(b.value)) %>
						  <%= b.text %>
						<% end %>
					  </div>
					<% end %>
				<% end %>
              </form>
            </div> <!-- panel-body -->
          </div> <!-- subcategories-checkbox -->
        </div> <!-- panel-default -->
        <%= render :partial => "articles/articlefaq" %>
      </div> <!-- panel-group -->
    </div> <!-- col-md-3 -->
  </div> <!-- row -->
</div> <!-- container -->

<% if Rails.env.development? %>
  <code><%= article.try(:to_sir_trevor) %></code>
<% end %>

app/views/articles/edit.html.erb
<% title "Edit #{@article.title}" %>
<%= render partial: 'articles/form', locals: {article: @article} %>

app/views/articles/index.html.erb
<% title 'Articles' %>

<%#
    The following lines check to see if there is a search query.  If there is
    than search results will be displayed.  If there isn't a query than a list
    of categories will be shown instead
#%>
<% if params[:q].present? || params[:cat_id].present? %>
  <div class='container'>
  <h1 class='text-center'>
    Search Results
  </h1>
  <% @articles.each do |article| %>
    <div style='padding: 20px; margin-left: 10%'>
      <h3>
        <%= link_to article.title, article %>
      </h3>
      <h5>
        <%= article.excerpt %>...
        <%= link_to 'Read More', article %>
      </h5>
      <p>
        Part of:
        <i>
          <% article.subcategories.each do |scat| %>
            <%= link_to scat.name, scat %>
          <% end %>
        </i>
      </p>
    </div>
  <% end %>
  </div>
<% else %>
  <div class='container'>
    <h1 class='text-center'>
      Listing Articles
    </h1>
    <hr>
    <% @categories.each do |category| %>
      <div class='col-md-2'>
        <div>
          <h4>
            <strong>
              <%= link_to category.name, category, :style => "color:#551A8B;" %>
            </strong>
          </h4>
          <hr>
          <% category.subcategories.each do |subcategory| %>
            <h5>
              <strong>
                <%= link_to subcategory.name, subcategory, :style => "color:#A25F08;font-size:1.2em;" %>
              </strong>
            </h5>
            <% subcategory.articles.each do |article| %>
              <h6>
		<strong>
                <%= link_to article.title, article, :style => "font-size:1.2em;" %>
		</strong>
	      </h6>
            <% end %>
            <hr>
          <% end %>
        </div>
      </div>
    <% end %>
  </div>
<% end %>

app/views/articles/new.html.erb
<% title "New Article" %>

<%= render partial: 'articles/form', locals: {article: Article.new} %>

<%= link_to 'Back', articles_path %>

app/views/articles/show.html.erb
<% title "#{@article.title}" %>
<div class="container">
  <div class="pull-right">
    <% if user_signed_in? %>
      <%= link_to "Edit", edit_article_path(@article), class: 'btn btn-default' %>
    <% end %>
  </div>
  <h2 class="page-header"><%= @article.title %></h2>
  <div class="col-md-12">
    <% @article.blocks.each do |block| %>
      <%= render partial: "articles/blocks/#{block.slug}", locals: {block: block.specific} %>
    <% end %>
  </div>
  <div class='col-md-12'>
    <hr>
    <h3>
      Related Pages:
    </h3>
    <% @related = Article.first(5) if @related.blank? %>
      <ul>
        <% @related[1..6].each do |article| %>
          <li>
            <%= link_to article.title, article %>
          </li>
        <% end %>
      </ul>
  </div>
</div>